name: Hello World!

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello World!"
      
      - name: Display current date and time
        run: date
        
      - name: List directory contents
        run: ls -l
