name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Render
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ctr4rgtds78s73di8gug?key=PHDwIHvFC80}}
          apiKey: ${{rnd_TwtBrNzRdmnSUmywGTPy9TAq2Mqm }}
          multipleDeployment: false
