name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ https://api.render.com/deploy/srv-ctr4rgtds78s73di8gug?key=PHDwIHvFC80}}
          apiKey: ${{ rnd_TwtBrNzRdmnSUmywGTPy9TAq2Mqm }}
          multipleDeployment: false
